version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    labels:
      name: fbid.mongo
      description: "FBID (MUIRST - ETSIT - UPM) final assigment - Mongo container"
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fbid

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    labels:
      name: fbid.mongo-express
      description: "FBID (MUIRST - ETSIT - UPM) final assigment - Mongo express container"
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: fbid
      ME_CONFIG_MONGODB_URL: mongodb://root:fbid@mongo:27017/

  # web:
  #   # build:
  #     # Aqui hace falta hacer un Dockerfile e instalar las dependencias de "requirements.txt".
  #     context:
  #     dockerfile:
  #   container_name: web
  #   labels:
  #     name: fbid.web
  #     description: "FBID (MUIRST - ETSIT - UPM) final assigment - Flask web container"
  #   depends_on:
  #     - mongo
  #     - mongo-express

  # zookeeper:
  #   image: zookeeper:3.6.3
  #   hostname: zookeeper
  #   container_name: zookeeper
  #   labels:
  #     name: fbid.zoo1
  #     description: "FBID (MUIRST - ETSIT - UPM) final assigment - Zookeeper node"
  #   # command: sh -c "bin/zookeeper-server-start.sh config/zookeeper.properties"
  #   restart: always
  #   ports:
  #     - 2181:2181


  kafka:
    image: "bitnami/kafka:3.0.0"
    container_name: kafka
    labels:
      name: fbid.kafka
      description: "FBID (MUIRST - ETSIT - UPM) final assigment - Kafka node"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    # depends_on:
    #   - zookeeper
# Tres nodos zooekeeper? O con uno vale?
# Un nodo kafka por cada nodo zk? Cada uno se conecta al correspondiente nodo zk? O todos a uno? O un solo nodo kafka?
# La version tiene que ser 2.12-3.0.0. Hay dos repos en docker-hub. Uno no ha actualizado hasta esa versión y la otra solo especifica el 3.0.0
# Creo que el 2.12 hace referencia a la version de scala que utiliza, pero ni idea.
# Importante: usar el depends_on: zoo1, zoo2, zoo3 (o zookeeper si solo hay un nodo)

# zoo1:
#   image: zookeeper:3.6.3
#   hostname: zoo1
#   container_name: zookeeper1
#   labels:
#     name: fbid.zoo1
#     description: "FBID (MUIRST - ETSIT - UPM) final assigment - Zookeeper node 1"
#   restart: always
#   ports:
#     - 2181:2181
#   environment:
#     ZOO_MY_ID: 1
#     ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

# zoo2:
#   image: zookeeper:3.6.3
#   hostname: zoo2
#   container_name: zookeeper2
#   labels:
#     name: fbid.zoo2
#     description: "FBID (MUIRST - ETSIT - UPM) final assigment - Zookeeper node 2"
#   restart: always
#   ports:
#     - 2182:2181
#   environment:
#     ZOO_MY_ID: 2
#     ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

# zoo3:
#   image: zookeeper:3.6.3
#   hostname: zoo3
#   container_name: zookeeper3
#   labels:
#     name: fbid.zoo3
#     description: "FBID (MUIRST - ETSIT - UPM) final assigment - Zookeeper node 3"
#   restart: always
#   ports:
#     - 2183:2181
#   environment:
#     ZOO_MY_ID: 3
#     ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

#  kafka:
#   image: 'bitnami/kafka:latest'
#   ports:
#     - '9092:9092'
#   environment:
#     - KAFKA_BROKER_ID=1
#     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#     - ALLOW_PLAINTEXT_LISTENER=yes
#   depends_on:
#     - zookeeper

# networks:
# volumes:

# example:
# image:
# build:
# context:
# dockerfile:
# container_name: web
# labels:
#   name: fbid.web
#   description: "FBID (MUIRST - ETSIT - UPM) final assigment - Flask web container"
# depends_on:
# deploy:
#   replicas: 6
#   placement:
#     max_replicas_per_node: 1
#   update_config:
#     parallelism: 2
#     delay: 10s
#   restart_policy:
#     condition: on-failure
# restart: always

# #########################################
# version: "3.9"

# services:
#   db:
#     image: mysql:5.7
#     container_name: 'test_db'
#     restart: 'always'
#     volumes:
#       - db_data:/var/lib/mysql
#     ports:
#       - "3306"
#     environment:
#       MYSQL_DATABASE: wordpress_db_test
#       MYSQL_ROOT_PASSWORD: testpw123
#       MYSQL_USER: wordpress_test
#       MYSQL_PASSWORD: testpw123

#   wordpress:
#     image: wordpress:latest
#     container_name: 'test_wordpress'
#     restart: 'always'
#     ports:
#       - "5000:80"
#     volumes:
#       - wordpress_data:/var/www/html
#     links:
#       - db
#     environment:
#       WORDPRESS_DB_HOST: db:3306
#       WORDPRESS_DB_USER: wordpress_test
#       WORDPRESS_DB_PASSWORD: testpw123
#       WORDPRESS_DB_NAME: wordpress_db_test
# volumes:
#   db_data:
#   wordpress_data:
