version: "3.9"
services:

# zk
# kafka ---<
# mongo ----<
# web
# spark worker
# spark master
# spark submit

 zookeeper:
    build:
          context: ./docker
          dockerfile: Dockerfile.zk
    hostname: zoo
    container_name: zoo
    labels:
      name: fbid.zoo
      description: "FBID (MUIRST - ETSIT - UPM) final assigment - Zookeeper node"
    restart: always
    ports:
      - 2181:2181

  kafka:
    build:
          context: ./docker
          dockerfile: Dockerfile.kafka
    container_name: kafka
    labels:
      name: fbid.kafka
      description: "FBID (MUIRST - ETSIT - UPM) final assigment - Kafka node"
    ports:
      - "9092:9092"
    command: sh -c "/kafka/bin/kafka-topics.sh \
      --create \
      --bootstrap-server localhost:9092 \
      --replication-factor 1 \
      --partitions 1 \
      --topic flight_delay_classification_request"
    depends_on:
      - zookeeper


  mongo:
    image: mongo
    container_name: mongo
    labels:
      name: fbid.mongo
      description: "FBID (MUIRST - ETSIT - UPM) final assigment - Mongo container"
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fbid

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    labels:
      name: fbid.mongo-express
      description: "FBID (MUIRST - ETSIT - UPM) final assigment - Mongo express container"
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: fbid
      ME_CONFIG_MONGODB_URL: mongodb://root:fbid@mongo:27017/

 

  # web:
  #   # build:
  #     # Aqui hace falta hacer un Dockerfile e instalar las dependencias de "requirements.txt".
  #     context:
  #     dockerfile:
  #   container_name: web
  #   labels:
  #     name: fbid.web
  #     description: "FBID (MUIRST - ETSIT - UPM) final assigment - Flask web container"
  #   depends_on:
  #     - mongo
  #     - mongo-express

 
