# We choose this base image over a standar ubuntu/alpine version because this one has python3, pip, and the requirements.txt already installed.
# We won't use Spark here though
FROM fbid.spark

COPY . /fbid

WORKDIR /fbid/resources/web

ENV PROJECT_HOME=/fbid

CMD ["python3","predict_flask.py"]