FROM mongo:5.0.3

EXPOSE 27017

RUN mkdir flights \
    && cd flights \
    && mkdir data && mkdir db

# VOLUME /flights/db

WORKDIR /flights

COPY resources/import_distances.sh import_distances.sh
COPY docker/resources/origin_dest_distances.jsonl data/origin_dest_distances.jsonl

COPY docker/mongo.sh /mongo.sh

RUN chmod +x /mongo.sh

CMD ["/mongo.sh"]

