FROM fbid.spark

COPY . /fbid
WORKDIR /fbid/resources/airflow

EXPOSE 8000

RUN pip install -r requirements.txt -c constraints.txt
ENV PROJECT_HOME=/

ENV AIRFLOW_HOME=/fbid/resources/airflow
RUN mkdir ${AIRFLOW_HOME}/dags
RUN mkdir ${AIRFLOW_HOME}/logs
RUN mkdir ${AIRFLOW_HOME}/plugins
RUN airflow db init
RUN cp setup.py ${AIRFLOW_HOME}/dags/

CMD ["bash", "start_airflow.sh"]
