FROM fbid.spark

WORKDIR /opt/spark

# EXPOSE 8085

COPY . /fbid

COPY docker/resources/flight_prediction_2.12-0.1.jar /jar/flight_prediction_2.12-0.1.jar

RUN chmod +x /jar/flight_prediction_2.12-0.1.jar

COPY docker/spark-submit.sh /spark-submit.sh

RUN chmod +x /spark-submit.sh

CMD ["/spark-submit.sh"]

